name: raptgen

channels:
  - bioconda
  - conda-forge

dependencies:
  - gcc=12.1.0
  - pandas
  - numpy
  - matplotlib
  - pytorch=1.12.1
  - scikit-learn
  - biopython=1.78
  - centroid_rna_package=0.0.16
  - fastapi
  - uvicorn
  - ipykernel
  - ipython
  - jupyter
  - scipy
  - celery
  - redis-py
  - flower

variables:
  PYTHONPATH: /app

